#ifndef UTILS_H
#define UTILS_H
#include <stdint.h>
#include <stddef.h>

// This function handles errors generated by OpenSSL functions.
void handle_error_ssl();

// This function handles errors by printing a message and aborting the program.
void handle_error(const char *msg);

/* String Manipulation APIS */

// Convert unsigned char to hex string
void u8str(uint8_t x,uint8_t* out);

// Convert unsigned short int to hex string
void u16str(uint16_t x, uint8_t *out);

// Convert unsigned int to hex string
void u32str(uint32_t x, uint8_t *out);

// Convert hex string to unsigned int
uint32_t strTou32(const uint8_t *in);

// Interpret a byte string as a sequence of w-bit values
uint8_t coef(const uint8_t S[], size_t i, int w);

void hex_encode(const uint8_t *in, size_t len, char *out);

#endif // UTILS_H